Repository wecode-bootcamp-korea/36-backend-westagram, pull requests merged in 2022-08, with the labels that each got.

#3 [길성민-teamB] Assignment 1: Westagram Backend Project - Express 초기 환경세팅
  teamB/seongmin/westagram/.env.sample
  teamB/seongmin/westagram/.gitignore
  teamB/seongmin/westagram/app.js
  teamB/seongmin/westagram/package-lock.json
  teamB/seongmin/westagram/package.json
Labels: 완료

#14 [최종민 - teamB] Assignment 1 : Express API - 초기 환경 세팅
  teamB/jongmin_choi/.env.sample
  teamB/jongmin_choi/.gitignore
  teamB/jongmin_choi/app.js
  teamB/jongmin_choi/db/migrations/20220802032004_create_test_table.sql
  teamB/jongmin_choi/package-lock.json
  teamB/jongmin_choi/package.json
Labels: 멘토 리뷰 요청

#6 [류예린-teamB] Assignment 1: Express API - 초기 환경 세팅
  teamB/YaeRin/.env.sample
  teamB/YaeRin/.gitignore
  teamB/YaeRin/app.js
  teamB/YaeRin/package-lock.json
  teamB/YaeRin/package.json
Labels: 멘토 리뷰 요청, 수정 요청

#7 [정재하-teamA] Assignment 1: Express API - 초기환경 세팅
  teamA/jeongjaeha/.env.sample
  teamA/jeongjaeha/.gitignore
  teamA/jeongjaeha/app.js
  teamA/jeongjaeha/package-lock.json
  teamA/jeongjaeha/package.json
Labels: 수정 요청

#8 [문정진-teamB] Assignment 1: Express API - 초기 환경 세팅
  teamB/JungJin/.gitignore
  teamB/JungJin/app.js
  teamB/JungJin/db/migrations/20220801075736_users.sql
  teamB/JungJin/db/migrations/20220801075751_comments.sql
  teamB/JungJin/db/migrations/20220801075804_likes.sql
  teamB/JungJin/db/migrations/20220801075816_posts.sql
  teamB/JungJin/package-lock.json
  teamB/JungJin/package.json
Labels: 멘토 리뷰 요청, 수정 요청

#45 [최종민 - teamB] Assignment 2 : Express API - 유저 회원가입하기
  teamB/jongmin_choi/app.js
  teamB/jongmin_choi/db/migrations/20220803031017_create_users_table.sql
Labels: 멘토 리뷰 요청

#4 [이상우-teamB] Assignment 1: Express API - 초기 환경 세팅
  teamB/sangwoo/.env.sample
  teamB/sangwoo/.gitignore
  teamB/sangwoo/app.js
  teamB/sangwoo/package-lock.json
  teamB/sangwoo/package.json
Labels: 멘토 리뷰 요청, 수정 요청

#20 [이지현-teamA] Assignment 1: Express 초기 환경세팅
  teamA/jihyun/.env.sample
  teamA/jihyun/.gitignore
  teamA/jihyun/app.js
  teamA/jihyun/db/migrations/20220802053241_create_users_table.sql
  teamA/jihyun/db/migrations/20220802053253_create_posts_table.sql
  teamA/jihyun/db/migrations/20220802053305_create_posts_users_table.sql
  teamA/jihyun/package-lock.json
  teamA/jihyun/package.json
Labels: 멘토 리뷰 요청

#48 [정세한-teamA] Assignment 1: Express API - 초기 환경 세팅
  teamA/saehan/.env.sample
  teamA/saehan/.gitignore
  teamA/saehan/app.js
  teamA/saehan/package-lock.json
  teamA/saehan/package.json
Labels: 멘토 리뷰 요청, 수정 요청

#9 [길성민-teamB] Assignment 2 | Westagram Backend Project - 유저 회원가입 하기
  teamB/seongmin/westagram/.env.sample
  teamB/seongmin/westagram/.gitignore
  teamB/seongmin/westagram/app.js
  teamB/seongmin/westagram/db/migrations/20220802004532_create_users.sql
  teamB/seongmin/westagram/db/migrations/20220802004632_create_posts.sql
  teamB/seongmin/westagram/db/migrations/20220802004731_create_likes.sql
  teamB/seongmin/westagram/package-lock.json
  teamB/seongmin/westagram/package.json
Labels: 멘토 리뷰 요청

#10 [문정진-teamB] Assignment 2: Express API - 유저 회원가입 하기
  teamB/JungJin/.gitignore
  teamB/JungJin/app.js
Labels: 멘토 리뷰 요청

#55 [최종민 - teamB] Assignment 3 : Express API - 게시물 등록하기
  teamB/jongmin_choi/app.js
  teamB/jongmin_choi/db/migrations/20220803074256_create_posts_table.sql
Labels: 멘토 리뷰 요청

#28 [이지현-teamA] Assignment 2: 유저 회원가입 하기
  teamA/jihyun/.env.sample
  teamA/jihyun/.gitignore
  teamA/jihyun/app.js
  teamA/jihyun/db/migrations/20220802053305_create_posts_users_table.sql
  teamA/jihyun/db/migrations/20220803134908_create_users_table.sql
  teamA/jihyun/db/migrations/20220803134924_create_posts_table.sql
  teamA/jihyun/db/migrations/20220804033505_update_posts_table.sql
  teamA/jihyun/package-lock.json
  teamA/jihyun/package.json
Labels: 멘토 리뷰 요청

#21 [류예린-teamB] Assignment 2: Westagram Backend Project - 유저 회원가입 하기
  teamB/YaeRin/.env.sample
  teamB/YaeRin/.gitignore
  teamB/YaeRin/app.js
  teamB/YaeRin/db/migrations/20220802034416_create_posts_table.sql
  teamB/YaeRin/db/migrations/20220802034427_create_users_table.sql
  teamB/YaeRin/package-lock.json
  teamB/YaeRin/package.json
Labels: 멘토 리뷰 요청

#35 [이상우-teamB] Assignment 2: Express API - 유저 회원가입 하기
  teamB/sangwoo/app.js
  teamB/sangwoo/db/migrations/20220802124749_create_users_table.sql
  teamB/sangwoo/db/migrations/20220802124756_create_posts_table.sql
  teamB/sangwoo/db/migrations/20220802124847_create_likes_table.sql
  teamB/sangwoo/package-lock.json
  teamB/sangwoo/package.json
Labels: 멘토 리뷰 요청

#57 [이석원-teamB] Assignment 1:EXPRESS API 초기환경셋팅
  teamB/sockwon/.env.sample
  teamB/sockwon/app.js
  teamB/sockwon/db/migrations/20220804022649_create_users_table.sql
  teamB/sockwon/db/migrations/20220804023253_create_posts_table.sql
  teamB/sockwon/db/migrations/20220804034337_create_likes_table.sql
  teamB/sockwon/db/migrations/20220804035649_create_comments.sql
  teamB/sockwon/package-lock.json
  teamB/sockwon/package.json
Labels: 수정 요청

#41 [박근우-teamA] Assignment 1: Express API - 초기 환경 세팅
  .gitignore
  app.js
  db/migrations/20220804042801_users.sql
  db/migrations/20220804042805_posts.sql
  package-lock.json
  package.json
Labels: 멘토 리뷰 요청

#77 [최종민 - teamB] Assignment 4 : Express API - 전체 게시글 조회하기
  teamB/jongmin_choi/app.js
Labels: 멘토 리뷰 요청

#61 [정세한-teamA] Assignment 2:유저 회원가입 하기
  teamA/saehan/.env.sample
  teamA/saehan/app.js
  teamA/saehan/db/migrations/20220803044724_create_users_table.sql
  teamA/saehan/db/migrations/20220803050357_create_posts_table.sql
  teamA/saehan/db/migrations/20220803050414_create_likes_table.sql
Labels: 멘토 리뷰 요청, 수정 요청

#34 [정재하 - teamA] Assignment :2 ExpressAPI - 유저 회원가입하기
  teamA/jeongjaeha/.env.sample
  teamA/jeongjaeha/.gitignore
  teamA/jeongjaeha/app.js
  teamA/jeongjaeha/db/migrations/20220802114625_create_users_table.sql
Labels: 멘토 리뷰 요청

#81 [이지현-teamA] Assignment 3: 게시글 등록하기
  teamA/jihyun/app.js
Labels: 멘토 리뷰 요청

#12 [문정진-teamB] Assignment 4: Express API - 전체 게시글 조회하기
  teamB/JungJin/app.js
Labels: 멘토 리뷰 요청

#86 [길성민-teamB] Assignment: Express API CRUD 전체 기능
  teamB/seongmin/westagram/app.js
  teamB/seongmin/westagram/db/migrations/20220805033912_modify_likes.sql
Labels: 멘토 리뷰 요청

#92 [문정진-teamB] Assignment: Express API CRUD 전체 기능
  teamB/JungJin/app.js
  teamB/JungJin/db/migrations/20220805074421_likes_1.sql
Labels: 멘토 리뷰 요청

#84 [이상우-teamB] Assignment: Express API CRUD 전체 기능
  teamB/sangwoo/app.js
  teamB/sangwoo/db/migrations/20220805044402_create_unique_table.sql
Labels: 멘토 리뷰 요청

#85 [류예린-teamB] Assignment: Express API CRUD 전체 기능
  teamB/YaeRin/.DS_Store
  teamB/YaeRin/app.js
  teamB/YaeRin/db/migrations/20220805045016_create_users_table.sql
  teamB/YaeRin/db/migrations/20220805045022_create_posts_table.sql
  teamB/YaeRin/db/migrations/20220805045028_create_likes_table.sql
  teamB/YaeRin/db/migrations/20220805050049_plusunique.sql
  teamB/YaeRin/db/schema.sql
Labels: 멘토 리뷰 요청

#89 [정재하 - teamA] Assignment: Express API CRUD 전체 기능
  teamA/jeongjaeha/.env.sample
  teamA/jeongjaeha/.gitignore
  teamA/jeongjaeha/app.js
  teamA/jeongjaeha/db/migrations/20220802114625_create_users_table.sql
  teamA/jeongjaeha/db/migrations/20220806060445_create_users_table.sql
  teamA/jeongjaeha/db/migrations/20220806060451_create_posts_table.sql
  teamA/jeongjaeha/db/migrations/20220806060457_create_likes_table.sql
  teamA/jeongjaeha/db/migrations/20220806060630_create_ckeck_like_table.sql
  teamA/jeongjaeha/package-lock.json
  teamA/jeongjaeha/package.json
Labels: 멘토 리뷰 요청

#91 [백민석 teamB] Assignment Api CRUD 전체 구현하기
  teamB/minseok/.env.sample
  teamB/minseok/.gitignore
  teamB/minseok/app.js
  teamB/minseok/db/migrations/20220803054156_users_table.sql
  teamB/minseok/db/migrations/20220803114518_posts.sql
  teamB/minseok/db/migrations/20220804133243_likes.sql
  teamB/minseok/db/migrations/20220806054019_likesUNIQUE.sql
  teamB/minseok/package-lock.json
  teamB/minseok/package.json
Labels: 멘토 리뷰 요청

#95 [박명호 teamB] Assignment: Express API CRUD 전체 기능
  .DS_Store
  teamA/.DS_Store
  teamB/.DS_Store
  teamB/parkmyungho/.DS_Store
  teamB/parkmyungho/.env.sample
  teamB/parkmyungho/README.md
  teamB/parkmyungho/app.js
  teamB/parkmyungho/db/.DS_Store
  teamB/parkmyungho/db/schema.sql
Labels: 멘토 리뷰 요청

#93 [이지현 teamA] Assignment: Express API CRUD 전체 기능
  teamA/jihyun/app.js
  teamA/jihyun/db/migrations/20220805011220_create_like_table.sql
  teamA/jihyun/db/migrations/20220805012728_update_posts_table.sql
  teamA/jihyun/db/migrations/20220805012737_update_likes_table.sql
  teamA/jihyun/db/migrations/20220805033338_update_likes_table.sql
  teamA/jihyun/db/migrations/20220807050030_update_users_table.sql
Labels: 멘토 리뷰 요청

#88 [최종민 - teamB] Assignment : Express API CRUD 전체 기능
  .DS_Store
  teamB/.DS_Store
  teamB/jongmin_choi/app.js
  teamB/jongmin_choi/db/migrations/20220804130031_create_likes_table.sql
  teamB/jongmin_choi/db/migrations/20220805033155_add_unique_condition_to_likes_table.sql
  teamB/jongmin_choi/db/migrations/20220805043054_recreate_likes_table.sql
  teamB/jongmin_choi/db/migrations/20220808035520_create_likes_table_v2.sql
Labels: 멘토 리뷰 요청

#96 [정세한 teamA] Assignment: Express API CRUD 전체 기능
  teamA/saehan/app.js
Labels: Conflict 해결 요청

#98 [박근우-teamA] Assignment: Express API CRUD 전체 기능
  .gitignore
  app.js
  db/migrations/20220803025742_users.sql
  db/migrations/20220803025744_posts.sql
  db/migrations/20220805035859_likes.sql
  env.sample
  package-lock.json
  package.json
Labels: 멘토 리뷰 요청

#99 [길성민-teamB] Assignment: Layered-pattern 구현
  teamB/seongmin/westagram/.gitignore
  teamB/seongmin/westagram/app.js
  teamB/seongmin/westagram/controllers/likeController.js
  teamB/seongmin/westagram/controllers/postController.js
  teamB/seongmin/westagram/controllers/userController.js
  teamB/seongmin/westagram/models/daoUtil.js
  teamB/seongmin/westagram/models/likeDao.js
  teamB/seongmin/westagram/models/postDao.js
  teamB/seongmin/westagram/models/userDao.js
  teamB/seongmin/westagram/package.json
  teamB/seongmin/westagram/routes/idex.js
  teamB/seongmin/westagram/routes/likeRoute.js
  teamB/seongmin/westagram/routes/postRoute.js
  teamB/seongmin/westagram/routes/userRoute.js
  teamB/seongmin/westagram/services/likeService.js
  teamB/seongmin/westagram/services/postSearchService.js
  teamB/seongmin/westagram/services/postService.js
  teamB/seongmin/westagram/services/userService.js
Labels: 멘토 리뷰 요청

#100 [최종민 - teamB] Assignment : Layered 패턴 적용
  teamB/jongmin_choi/app.js
  teamB/jongmin_choi/controllers/postController.js
  teamB/jongmin_choi/controllers/userController.js
  teamB/jongmin_choi/models/dataSource.js
  teamB/jongmin_choi/models/postDao.js
  teamB/jongmin_choi/models/userDao.js
  teamB/jongmin_choi/routes/index.js
  teamB/jongmin_choi/routes/postRouter.js
  teamB/jongmin_choi/routes/userRouter.js
  teamB/jongmin_choi/services/postService.js
  teamB/jongmin_choi/services/userService.js
Labels: 멘토 리뷰 요청

#102 [이상우 - teamB] Assignment : Project Structure (Layered Pattern)
  teamB/sangwoo/app.js
  teamB/sangwoo/controllers/postController.js
  teamB/sangwoo/controllers/userController.js
  teamB/sangwoo/db/migrations/20220805044402_create_unique_table.sql
  teamB/sangwoo/models/dataSource.js
  teamB/sangwoo/models/postDao.js
  teamB/sangwoo/models/userDao.js
  teamB/sangwoo/routes/index.js
  teamB/sangwoo/routes/postRouter.js
  teamB/sangwoo/routes/userRouter.js
  teamB/sangwoo/services/postService.js
  teamB/sangwoo/services/userService.js
Labels: 멘토 리뷰 요청

#105 [문정진 - teamB] Assignment: Project Layered pattern 적용
  teamB/JungJin/app.js
  teamB/JungJin/controllers/likeController.js
  teamB/JungJin/controllers/postController.js
  teamB/JungJin/controllers/userController.js
  teamB/JungJin/db/migrations/20220805085406_likes_1.sql
  teamB/JungJin/models/database.js
  teamB/JungJin/models/likeDao.js
  teamB/JungJin/models/postDao.js
  teamB/JungJin/models/userDao.js
  teamB/JungJin/routes/index.js
  teamB/JungJin/routes/likeRouter.js
  teamB/JungJin/routes/postRouter.js
  teamB/JungJin/routes/userRouter.js
  teamB/JungJin/services/likeService.js
  teamB/JungJin/services/postService.js
  teamB/JungJin/services/userService.js
Labels: 멘토 리뷰 요청

#103 [류예린 - teamB] Assignment : Project Layered pattern 적용
  teamB/YaeRin/.DS_Store
  teamB/YaeRin/.env.sample
  teamB/YaeRin/.gitignore
  teamB/YaeRin/app.js
  teamB/YaeRin/controllers/postController.js
  teamB/YaeRin/controllers/userController.js
  teamB/YaeRin/db/migrations/20220805045028_create_likes_table.sql
  teamB/YaeRin/db/migrations/20220805050049_plusunique.sql
  teamB/YaeRin/db/migrations/20220809024145_create_users_table.sql
  teamB/YaeRin/db/migrations/20220809024152_create_posts_table.sql
  teamB/YaeRin/db/migrations/20220809024159_create_likes_table.sql
  teamB/YaeRin/db/migrations/20220809024205_create_comments_table.sql
  teamB/YaeRin/models/dataSource.js
  teamB/YaeRin/models/postDao.js
  teamB/YaeRin/models/userDao.js
  teamB/YaeRin/routes/index.js
  teamB/YaeRin/routes/postRouter.js
  teamB/YaeRin/routes/userRouter.js
  teamB/YaeRin/services/postService.js
  teamB/YaeRin/services/userService.js
Labels: 멘토 리뷰 요청

#106 [길성민 - teamB] Assignment: Error Handling 적용
  teamB/seongmin/westagram/controllers/likeController.js
  teamB/seongmin/westagram/controllers/userController.js
  teamB/seongmin/westagram/models/postDao.js
  teamB/seongmin/westagram/models/userDao.js
  teamB/seongmin/westagram/services/likeService.js
  teamB/seongmin/westagram/services/postSearchService.js
  teamB/seongmin/westagram/services/postService.js
Labels: 멘토 리뷰 요청

#101 [이지현 - teamA] Assignment : Project Layered pattern 적용
  teamA/jihyun/app.js
  teamA/jihyun/controllers/postController.js
  teamA/jihyun/controllers/userController.js
  teamA/jihyun/models/dataSource.js
  teamA/jihyun/models/postDao.js
  teamA/jihyun/models/userDao.js
  teamA/jihyun/routes/index.js
  teamA/jihyun/routes/postRouter.js
  teamA/jihyun/routes/userRouter.js
  teamA/jihyun/services/postService.js
  teamA/jihyun/services/userService.js
Labels: 멘토 리뷰 요청

#104 [정재하- teamA] Assignment : Project Layered Pattern 적용
  teamA/jeongjaeha/app.js
  teamA/jeongjaeha/controllers/postController.js
  teamA/jeongjaeha/controllers/userController.js
  teamA/jeongjaeha/db/migrations/20220806060630_create_ckeck_like_table.sql
  teamA/jeongjaeha/models/Database.js
  teamA/jeongjaeha/models/postDao.js
  teamA/jeongjaeha/models/userDao.js
  teamA/jeongjaeha/package-lock.json
  teamA/jeongjaeha/package.json
  teamA/jeongjaeha/routers/index.js
  teamA/jeongjaeha/routers/postRouter.js
  teamA/jeongjaeha/routers/userRouter.js
  teamA/jeongjaeha/services/postServices.js
  teamA/jeongjaeha/services/userServices.js
Labels: 멘토 리뷰 요청

#107 [백민석- teamB] Assignment : Project Layered Pattern 적용
  teamB/minseok/Controller/likesControllers.js
  teamB/minseok/Controller/postsController.js
  teamB/minseok/Controller/userController.js
  teamB/minseok/app.js
  teamB/minseok/models/likesDao.js
  teamB/minseok/models/myDataSource.js
  teamB/minseok/models/postsDao.js
  teamB/minseok/models/userDao.js
  teamB/minseok/routes/index.js
  teamB/minseok/routes/likesRouter.js
  teamB/minseok/routes/postsRouter.js
  teamB/minseok/routes/userRouter.js
  teamB/minseok/service/likesService.js
  teamB/minseok/service/postsService.js
  teamB/minseok/service/userService.js
Labels: 멘토 리뷰 요청

#110 [정세한- teamA] Assignment : Project Layered pattern 적용
  teamA/saehan/app.js
  teamA/saehan/controllers/likeController.js
  teamA/saehan/controllers/postController.js
  teamA/saehan/controllers/userController.js
  teamA/saehan/db/migrations/20220809040641_create_likes_table.sql
  teamA/saehan/models/likeDao.js
  teamA/saehan/models/postDao.js
  teamA/saehan/models/userDao.js
  teamA/saehan/routes/index.js
  teamA/saehan/routes/likeRouter.js
  teamA/saehan/routes/postRouter.js
  teamA/saehan/routes/userRouter.js
  teamA/saehan/services/likeService.js
  teamA/saehan/services/postService.js
  teamA/saehan/services/userService.js
  teamA/saehan/utils/daoUtil.js
Labels: 멘토 리뷰 요청

#87 [이석원-teamB] Assignment: Express API CRUD 전체 기능
  teamB/sockwon/.gitignore
  teamB/sockwon/app.js
  teamB/sockwon/db/migrations/20220804022649_create_users_table.sql
  teamB/sockwon/db/migrations/20220804023253_create_posts_table.sql
  teamB/sockwon/db/migrations/20220804034337_create_likes_table.sql
  teamB/sockwon/db/migrations/20220804035649_create_comments.sql
  teamB/sockwon/db/migrations/20220806114829_create_likes_correction.sql
  teamB/sockwon/db/migrations/20220808102852_update_delete_cascade_on_likes_table.sql
Labels: 수정 요청

#111 [길성민 - teamB] Assignment: 인증 & 인가 적용
  teamB/seongmin/westagram/controllers/postController.js
  teamB/seongmin/westagram/controllers/userController.js
  teamB/seongmin/westagram/models/userDao.js
  teamB/seongmin/westagram/package-lock.json
  teamB/seongmin/westagram/package.json
  teamB/seongmin/westagram/routes/userRoute.js
  teamB/seongmin/westagram/services/postService.js
  teamB/seongmin/westagram/services/userService.js
Labels: 멘토 리뷰 요청

#112 [박근우-teamA] layered되지 않은 app.js merge 신청
  teamA/GeunWoo/.gitignore
  teamA/GeunWoo/app.js
  teamA/GeunWoo/db/migrations/20220803025742_users.sql
  teamA/GeunWoo/db/migrations/20220803025744_posts.sql
  teamA/GeunWoo/db/migrations/20220805035859_likes.sql
  teamA/GeunWoo/env.sample
  teamA/GeunWoo/package-lock.json
  teamA/GeunWoo/package.json
Labels: 멘토 리뷰 요청

#113 [문정진 - teamB] Assignment: 인증 & 인가 적용
  teamB/JungJin/controllers/userController.js
  teamB/JungJin/db/migrations/20220810080556_users_1.sql
  teamB/JungJin/middlewares/auth.js
  teamB/JungJin/models/userDao.js
  teamB/JungJin/package-lock.json
  teamB/JungJin/package.json
  teamB/JungJin/routes/postRouter.js
  teamB/JungJin/routes/userRouter.js
  teamB/JungJin/services/userService.js
Labels: 멘토 리뷰 요청

#118 [박근우-teamA] Layered architecture와 Error Handling 적용
  teamA/GeunWoo/app.js
  teamA/GeunWoo/controllers/likeController.js
  teamA/GeunWoo/controllers/postController.js
  teamA/GeunWoo/controllers/userController.js
  teamA/GeunWoo/models/dataSource.js
  teamA/GeunWoo/models/likeDao.js
  teamA/GeunWoo/models/postDao.js
  teamA/GeunWoo/models/userDao.js
  teamA/GeunWoo/routes/index.js
  teamA/GeunWoo/routes/likeRouter.js
  teamA/GeunWoo/routes/postRouter.js
  teamA/GeunWoo/routes/userRouter.js
  teamA/GeunWoo/services/likeService.js
  teamA/GeunWoo/services/postService.js
  teamA/GeunWoo/services/userService.js
Labels: 멘토 리뷰 요청
